---
- hosts: webservers
  become: true
  tasks: 
  - name: "Copy workload file to remode server"
    copy:
      src: /var/lib/jenkins/workspace/maven-pipeline/deploy.yml
      dest: /home/ec2-user
      owner: ec2-user
      group: ec2-user
      mode: 0644
  - name: "change to working directory"
    args:
      chdir: home/ec2-user
  - name: "Deploying application to target nodes"
    command: kubectl apply -f deploy.yml
